title: Jerzy Łazor
url: "./"
baseurl: ""

markdown: kramdown
ins_logo: "./sgh_logo.png"

tracking_id: #

footer: yes
footer_url: "https://github.com/ankitsultana"
footer_text: "Page design by Ankit Sultana"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "O mnie"
   link: "./"
 - name: "About me"
   link: ""
 - name: "Kontakt"
   link: "contact"
